### ISSUE TITLE
Stale Flags, and flags not getting removed

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#109]
While playing around with flags I discovered an issue with flags not being removed / updated if third party sources where responsible for changing the flag, including if your own ai removed or moved a flag.

Should probably create a test ai script that places a flag, removes it and changes colors and such

**Comment by kurtish** [comment]
I will try to look into this one :)

**Comment by thmsndk** [comment]
The UnpackFlags method only unpacks flags, never cleans them up like UnpackRoomObjects does
https://github.com/thmsndk/Screeps3D/blob/ed90895b65948c4ea9e2686f51e68a3128254d4a/Assets/Scripts/Screeps3D/Rooms/RoomUnpacker.cs#L120-L142
