### ISSUE TITLE
Body part widget

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#116]
![image](https://user-images.githubusercontent.com/9084377/79043436-70f1e780-7bff-11ea-8f96-59057961a659.png)
The boosts could be visualized using different colours
So LO / LH would be green for example

colours from https://docs.screeps.com/resources.html
Every boost applies to one body part. If you boost two body parts then those parts are stronger but every unboosted part isn't affected.

UH / UO: #50D7F9
KH / KO: #A071FF
LH / LO: #00F4A2
ZH / ZO: #FDD388
GH / GO: #FFFFFF
![image](https://user-images.githubusercontent.com/9084377/79043462-9979e180-7bff-11ea-8426-17e509f82e67.png)

And the higher tiers get the same colours

- [x] Render body part count
- [x] Render basic body parts
- [x] visualize health of body parts
- [x] visualize boosts
- [x] handle updates
  - [x] updated hitpoints
  - [x] boosts
- [ ] Tooltip on body parts
- [ ] "Stats" for creep, e.g. potential dmg, health, carry and so forth

**Comment by thmsndk** [comment]
What about showing some relevant stats / numbers on the creep in relation to body parts, e.g. amount of potential dmg,healing and other bits that could be important.
Basicly including some of theese stats https://screeps.arcath.net/creep-designer

https://docs.screeps.com/api/#Creep

Feel free to comment with thoughts / ideas :)

**Comment by duckymirror** [comment]
That's a good idea! But as this would consume pretty much space which would be annoying with multiple selections I think it should be collapsible.

**Comment by thmsndk** [comment]
Making progress.. well kind of xD
![image](https://user-images.githubusercontent.com/9084377/79113954-51cf9300-7d82-11ea-93c8-fe4885fa28a9.png)

**Comment by thmsndk** [comment]
More progress
![image](https://user-images.githubusercontent.com/9084377/79116720-87c44580-7d89-11ea-99b1-df1f8aff6797.png)

**Comment by thmsndk** [comment]
@duckymirror do you mean the entire body part widget should be collapsible? or only the stats we where discussing?

In general I feel that the selection panel takes up a lot of screen estate. I wonder if things should be moved to an in world "hud" floating above selected structures / creeps 🤔 that is a subject for another issue though xD

**Comment by duckymirror** [comment]
I mean just the stats. When I select a creep I would like to see the basic information that is currently shown, the body parts and _sometimes_ the stats which I'd expand then.

I wouldn't let the panels float above the objects. If I wait for a rampart to be taken down and watch its hits go down I don't want to rotate the view until nothing I'd like to see is covered by the panel.

**Comment by thmsndk** [comment]
Now with color coded boost indicators
![image](https://user-images.githubusercontent.com/9084377/79919711-31ad6d00-842f-11ea-97c4-eee2670a6502.png)

And as an added feature, not enough height when there are 50 work parts ...
![image](https://user-images.githubusercontent.com/9084377/79920535-9a491980-8430-11ea-9aee-fa6febd34703.png)

**Comment by thmsndk** [comment]
Made some testcode to visualize the different boost effects on the body panel
![image](https://user-images.githubusercontent.com/9084377/80010492-c7e2a100-84ca-11ea-8453-f749fc2c6318.png)

**Comment by thmsndk** [comment]
Added scaling of hitpoints
![image](https://user-images.githubusercontent.com/9084377/80034230-62a0a700-84ee-11ea-8195-eadb0cab6deb.png)
