### ISSUE TITLE
List of nukes on shard

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#118]
With the experimental endpoint that detects nukes.
We wish to show a list of nukes for the current shard
This list should contain
- launch room
- target room
- estimated impact time

It should be possible to click the room to navigate to the room.
it should be possible to navigate to the nuke itself, in air.

if possible, Should "stats" be shown for a room to list number of attackers and amount of nukes for the target?

Other ideas / suggestions are welcome.

**Comment by thmsndk** [comment]
Hmm. how should we access this list of nukes? where do we click to show it?

**Comment by Helam24** [comment]
Using map stats to show the players involved as well instead of just the rooms

**Comment by thmsndk** [comment]
Well, it's progress. ugly compared to the observer mobile app, but progress nonetheless! screenshot taken 13-05-2020 00:03
![image](https://user-images.githubusercontent.com/9084377/81750070-2341f680-94ad-11ea-97b6-8089f81271d2.png)

**Comment by thmsndk** [comment]
The observer iOS app nuke list for inspiration :)
![image](https://user-images.githubusercontent.com/9084377/81834663-88dfc280-9541-11ea-9922-2e18888d7691.png)

**Comment by thmsndk** [comment]
@Helam24 Does that mean you call map-stats 3 times when opening this view? one time for each shard? with all launch and impact rooms?

**Comment by thmsndk** [comment]
Hmmm I just had an idea, this is the WIP so far. but notice Christinayo is nuking the hell out of W24N16. e.g multiple nukes for the same target. should we group them up and write X nukes on the way to the target, with the ability to fold it out and see who is nuking them? perhaps render badge / label for everyone attacking the room when it is collabsed? 🤔 sort of a "summary" for the target?
![image](https://user-images.githubusercontent.com/9084377/81894370-dd218b80-95af-11ea-996e-bad53378c6c4.png)

**Comment by Helam24** [comment]
@thmsndk sorry for the slow replies lately. Yes I believe I do call map stats 3 times like you said. I had thought of that summary thing as well as there can be a lot of duplication but didn't end up doing it. Could have it listed a number of ways, like instead of one row per nuke, it could be one row per defending player, or per attacking player, with summaries of the nukes under them. Either could be cool but for simplicity (or laziness) i'm gonna leave it the same for now haha.

**Comment by thmsndk** [comment]
I think this is gonna be the "final" product for this iteration.
![image](https://user-images.githubusercontent.com/9084377/82676698-19f02100-9c47-11ea-9055-5b95c04c33eb.png)
