### ISSUE TITLE
Mismatch in models & prefabs

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#13]
- [x] constructionsite - how does it work?
- [x] added rampart and wall model to RoomObjects scene. AFAIK the scene is just for preview purposes and is not related to how the client is working.
- [x] dropped resources rendering
- [x] removed MissingPrefabs
- [x] A few prefabs has their "origin": tower, link and lab have their origin rendered oddly because of LineRenderer->Use World Space, not sure if we need to change it

**Comment by Robalian** [comment]
gimme

**Comment by Robalian** [comment]
tower, link and lab have their origin rendered oddly because of LineRenderer->Use World Space

**Comment by Robalian** [comment]
Construction sites are using 2D square canvas and render images masked by `Image.FillMethod.Radial360`
