### ISSUE TITLE
HDRP - Verify that HDRP can run on mac & linux

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#142]
We need to verify that HDRP builds can run on both Mac and Linux.
We probably need to make some test builds. Perhaps together with the next release. that people can try out 🤔

**Comment by thmsndk** [comment]
Mac:
https://forum.unity.com/threads/error-while-setting-up-hd-rendering-pipeline-on-mac.540830/

**Comment by Flya** [comment]
I have tried this solution, but I can't found metal option in settings.

**Comment by thmsndk** [comment]
@Flya https://docs.unity3d.com/Manual/Metal.html this might help :)

**Comment by Flya** [comment]
I have tried this too, but not able to build it. But I don't spend a lot of time on this one.

**Comment by thmsndk** [comment]
https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@8.1/manual/index.html

> HRDP is only supported on the following platforms:
> 
> Windows and Windows Store, with DirectX 11 or DirectX 12 and Shader Model 5.0
> Modern consoles (Sony PS4 and Microsoft Xbox One)
> MacOS using Metal graphics
> Linux and Windows platforms with Vulkan
> HDRP does not support OpenGL or OpenGL ES devices.
> 
> Note: HDRP only works on these platforms if the device used supports Compute Shaders.
>

**Comment by thmsndk** [comment]
I've build for Linux with Vulkan.

it fails to build for Mac with Metal as the only API with the following errors
![image](https://user-images.githubusercontent.com/9084377/82686315-f4b6df00-9c55-11ea-9ee3-43c3df4d806b.png)

**Comment by thmsndk** [comment]
Removed this package to fix that error `XR Legacy Input Helpers`
https://issuetracker.unity3d.com/issues/ubuntu-unityengine-dot-xr-dot-tango-error-stating-to-enable-an-already-enabled-built-in-package

cleared packages from teh package cache here as well 
https://docs.unity3d.com/Manual/upm-cache.html

**Comment by thmsndk** [comment]
It runs on both Linux and Mac
