### ISSUE TITLE
HDRP - smoke trail on nukes are broken

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#144]
![image](https://user-images.githubusercontent.com/9084377/81752286-7b7af780-94b1-11ea-887a-8c961d1f8116.png)

**Comment by Gadjung** [comment]
Will take a look of that. 
Does Nuke has 'owner' ?

**Comment by thmsndk** [comment]
@Gadjung here is what we recieve from the experimental endpoint, we have a launchRoom, and we know who the owner of that room is, unless it changes after the nuke has been launched.
https://github.com/thmsndk/Screeps3D/blob/72ee1aae388aa279c6646baa5b45c00d2170d878/Assets/Scripts/Screeps3D/NukeMonitor.cs#L209-L238

I'm not sure how the payload looks from the nuke object in the room subscription
this is the only issue so far about nukes https://github.com/thmsndk/Screeps3D/issues/58

**Comment by Gadjung** [comment]
ok, because i'm thinking on putting owner badge on a launched nuke this style :
![image](https://i.pinimg.com/originals/83/86/d8/8386d809ce60423281de061b9ee65701.jpg)

**Comment by Gadjung** [comment]
i guess can be closed ?
