### ISSUE TITLE
Bug - Camera goes nuts when nuke-view / no room found

### ISSUE THREAD

**Issue by Gadjung** [thmsndk/Screeps3D#146]
For now in Unity Game session
When login to Screeps official server
My room on S3 gets loaded properly (have 8 or 9 rooms in S3 only)
But aftera brief moment camera goes to view some nuke view
And get's blocked there

issue does not happen on S0/1/2

info from logs:
`Could not find any of your owned rooms :/
UnityEngine.Debug:Log(Object)
Screeps3D.Rooms.<FindPlayerOwnedRoom>d__21:MoveNext() (at Assets/Scripts/Screeps3D/Rooms/RoomChooser.cs:151)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)`

No relevant errors show up when this happens
switching shard, clicking PVP, Spectate, moving camera ,combination of said actions - nothing  changes (compass updates though)

video
https://screeps.slack.com/archives/CKL4441DW/p1589374990427500

**Comment by thmsndk** [comment]
What happens for you if you step trough this method with your user @Gadjung ?

https://github.com/thmsndk/Screeps3D/blob/54d190dd0986ecc3a136b23fcb5d1cb160dcda85/Assets/Scripts/Screeps3D/Rooms/RoomChooser.cs#L387-L468

What does the following return for you @Gadjung ? https://github.com/thmsndk/Screeps3D/blob/54d190dd0986ecc3a136b23fcb5d1cb160dcda85/Assets/Scripts/Screeps3D/Rooms/RoomChooser.cs#L137

**Comment by Gadjung** [comment]
ive put 
after line 137 :
`Debug.LogError("ScreepsAPI.Me.UserId: " + meUserId);`
`Debug.LogError("ownedRooms: " + ownedRooms.ToString());`


and in InitializeChooser in `if (shardObj != null) {`
`Debug.LogError("obj[\"shards\"]" + obj["shards"].ToString());`


line 137 do not fire at all
the obj[shards]:

```
obj["shards"]{"shard0":[],"shard1":[],"shard2":[],"shard3":["E21N59","E29N59","E31N45","E31N38","E32N59","E38N49","E31N49"]}
UnityEngine.Debug:LogError(Object)
```

**Comment by Gadjung** [comment]
got another exception:

```
Not allowed to override geometry on sprite ''
UnityEngine.Sprite:OverrideGeometry(Vector2[], UInt16[])
Unity.VectorGraphics.VectorUtils:BuildSprite(List`1, Rect, Single, Alignment, Vector2, UInt16, Boolean) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/VectorSprite.cs:119)
Unity.VectorGraphics.VectorUtils:BuildSprite(List`1, Single, Alignment, Vector2, UInt16, Boolean) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/VectorSprite.cs:72)
Screeps_API.BadgeManager:Texturize(String) (at Assets/Scripts/Screeps_API/BadgeManager.cs:88)
Screeps_API.BadgeManager:Generate(JSONObject, Single) (at Assets/Scripts/Screeps_API/BadgeManager.cs:162)
Screeps_API.UserManager:CacheUser(JSONObject) (at Assets/Scripts/Screeps_API/UserManager.cs:40)
Screeps3D.<UnpackUsers>d__8:MoveNext() (at Assets/Scripts/Screeps3D/MapStatsUpdater.cs:141)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Screeps3D.<UnpackMapStatsData>d__7:MoveNext() (at Assets/Scripts/Screeps3D/MapStatsUpdater.cs:74)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Screeps3D.MapStatsUpdater:GetMapStatsCallback(String) (at Assets/Scripts/Screeps3D/MapStatsUpdater.cs:66)
Screeps_API.<>c__DisplayClass4_0:<Request>b__0(UnityWebRequest) (at Assets/Scripts/Screeps_API/ScreepsHTTP.cs:106)
Screeps_API.<SendRequest>d__5:MoveNext() (at Assets/Scripts/Screeps_API/ScreepsHTTP.cs:127)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by Gadjung** [comment]
I have also multiple 
`target reached`, `target reached!` and `and we have a room` info messages one under another:
![image](https://user-images.githubusercontent.com/8514638/81821326-03a0e180-9532-11ea-88fe-ec2b8e0e2091.png)

**Comment by thmsndk** [comment]
@Gadjung Hmmm.
Could you look into when / why / how this is executed that is what triggers the target reached. 
https://github.com/thmsndk/Screeps3D/blob/54d190dd0986ecc3a136b23fcb5d1cb160dcda85/Assets/Scripts/Screeps3D/Player/PlayerTransporter.cs#L23-L38

Another interesting one is this one responsible for triggering the OnChooseRoom event, it is called from 5 places
https://github.com/thmsndk/Screeps3D/blob/54d190dd0986ecc3a136b23fcb5d1cb160dcda85/Assets/Scripts/Screeps3D/Rooms/RoomChooser.cs#L306-L321

**Comment by Gadjung** [comment]
![image](https://user-images.githubusercontent.com/8514638/81826334-f7b81e00-9537-11ea-899a-057b33bdd0aa.png)

after added error logging to TransportPlayer and to all invocations of `GetAndChooseRoom`

this are calls trigger by the moment of camera mess, no other logging is triggered later.

it's followed by room subscriptions, scanning sectors, getting mapStats 2500 and nukes information

**Comment by Gadjung** [comment]
i've commented-out 
```
// StartCoroutine(GetShardInfo());
// getNukes = GetNukes();
// StartCoroutine(getNukes);
```
and no more having a problem, will take a look there.

looks like it's the StartCoroutine(getNukes) that causes this, since just 
` StartCoroutine(GetShardInfo())` did not cause any issues

sometimes in GetNukes() 
`var shardIndex = PlayerPosition.Instance.ShardLevel;`
is getting 2 sometimes it's getting 3 despite that every time game loads same room on same shar (S3)

**Comment by thmsndk** [comment]
Hmmm PlayerPosition.Update sets the shardlevel based on how high the camera currently is. i've never experienced the kind of issue you are experiencing. and why on earth does GetNukes mess up your camera?

All it does it spawn the WorldMap Nuke overlay in world 🤔

**Comment by Gadjung** [comment]
looks like it's exactly this line
overlay = new NukeMissileOverlay(id);
in NukeMonitor

i commended everything:
![image](https://user-images.githubusercontent.com/8514638/81832075-613b2b00-953e-11ea-8b32-0e54bda67cc4.png)
and below, it was still causing problem. commented 
`// overlay = new NukeMissileOverlay(id);`
and all worked,
uncommented everything but the `overlay` stuff and it works also

**Comment by thmsndk** [comment]
Hmmm by newing up the NukeMisileOverlay I think it ends up calling this
https://github.com/thmsndk/Screeps3D/blob/54d190dd0986ecc3a136b23fcb5d1cb160dcda85/Assets/Scripts/Screeps3D/World/Views/NukeMissileView.cs#L18-L47

It does so because `WorldOverlay` calls Scheduler.Instance.Add(AssignView); And `WorldViewFactory.GetInstance` is called that ends up calling `view.Init`

**Comment by Gadjung** [comment]
looks like it's solved by setting proper rotation on Prefab - will push fix with hdrp_nuke branch

**Comment by Gadjung** [comment]
i guess can be closed ?
