### ISSUE TITLE
Badges are rendered upsidedown

### ISSUE THREAD

**Issue by Husenap** [thmsndk/Screeps3D#165]
3D client:
![image](https://user-images.githubusercontent.com/6496177/83957212-6bfb8e00-a866-11ea-9779-80789fe4fe45.png)

Official client:
![image](https://user-images.githubusercontent.com/6496177/83957225-7c136d80-a866-11ea-85d6-a877265e1cec.png)

**Comment by thmsndk** [comment]
As far as I recall badges are generated here 
https://github.com/thmsndk/Screeps3D/blob/9437ead0082494906a51452863eb67cb415fe06b/Assets/Scripts/Screeps_API/BadgeManager.cs#L124
