### ISSUE TITLE
Support for SK Lairs

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#18]
![official-source-keeper-lair](https://user-images.githubusercontent.com/9084377/59966314-16c25180-951b-11e9-8376-b1f2da5af3c1.gif)
We need to render Source Keeper lairs

https://docs.screeps.com/api/#StructureKeeperLair

**Model**
  - [x]  basic model (cylinder)
  - [x] "Advanced" model
  - [ ]  Animate pulsating "red"
  - [ ]  Visualize Next Spawn Time

**Info Panel**
  - [x]  Visualize Next Spawn Time
  - [x]  Show Owner as Source Keeper

**Comment by thmsndk** [comment]
smitt33 on slack pasted the following image
![image](https://user-images.githubusercontent.com/9084377/59968088-f357d080-9533-11e9-8ee0-be4e5c5a8c30.png)
That is a really good idea,we could perhaps make the "black" part, e.g. the inside of the "lair" pulsate with the red pulse like the official client

**Comment by Robalian** [comment]
How it should be rotated? Will it look good when rendered over a wall?

**Comment by thmsndk** [comment]
I think it should be rotated in such a way that the entrance is facing towards a plains or swamp tile, and yeah we should make sure the wall ain't clipping out the wrong places

Maybe we can procedurally generate them, I'm not sure how the heightmap is generated for the terrain 🤔

Alternatively we can just make sure to not render much around a lair and still plot it down, currently I'm just rendering a cylinder on top of it all, looks okay ish. Will provide screenshot later :)

**Comment by thmsndk** [comment]
In regards to rotating it, I'm thinking this
https://docs.unity3d.com/ScriptReference/Vector3.RotateTowards.html

**Comment by thmsndk** [comment]
This is currently what the keeperLair looks like in my feature branch, notice the one that is just standing inside the mountain top right, we probably need to modify terrain generation a little so it does not render terrain below keeper lairs 🤔 
![image](https://user-images.githubusercontent.com/9084377/59974168-2ee0b200-95a9-11e9-9a71-031806dea18a.png)

**Comment by Robalian** [comment]
Keeper lairs are normally slightly larger than a tile they're on, so it could partially solve the problem. What about using some non-directional model ("beacon" was mentioned on slack)?

**Comment by thmsndk** [comment]
Could use a beacon, I just don't feel like it fits that well as a lair, unless we are thinking some kind of "protoss teleport beacon esque" thing xD

**Comment by Robalian** [comment]
I though spirit portal from the less liked avatar series. More lairy lair would require modifying how the terrain looks, which might or might not be a problem.

**Comment by thmsndk** [comment]
I actually liked avatar xD
is this what you are thinking about?
https://avatar.fandom.com/wiki/Spirit_portal

I guess it also depends on the "lore" in screeps, I mean what is the source keepers, where do they come from? how should they be represented? - and such :)

**Comment by Robalian** [comment]
![image](https://user-images.githubusercontent.com/44264597/61741555-76698200-ad91-11e9-86d9-9ef7f440cd68.png)
![image](https://user-images.githubusercontent.com/44264597/61741774-e7109e80-ad91-11e9-9f37-3239bd8f5edf.png)

terrain deformation

**Comment by thmsndk** [comment]
That is looking pretty damn sweet  tbh!!

**Comment by Robalian** [comment]
![ezgif-2-8c0c9bad7732](https://user-images.githubusercontent.com/44264597/67855156-304f5780-fb12-11e9-9f5e-1dac7f5b6cb9.gif)
