### ISSUE TITLE
Support for Portals

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#19]
![official-portal](https://user-images.githubusercontent.com/9084377/63018424-18fcb880-be99-11e9-97ee-b9a73b82efd7.gif)

- [x] Basic model
  For starters a blue cylinder can represent a portal
- [x] Render on MapView
- [ ] Selection Pane
  - [x] Position
  - [x] Destination
    - [x] link to room
    - [x] link to room in another shard
- [ ] Blue glow

https://docs.screeps.com/api/#StructurePortal
> A non-player structure. Instantly teleports your creeps to a distant room acting as a room exit tile. Portals appear randomly in the central room of each sector.

Destination
>If this is an *inter-room* portal, then this property contains a RoomPosition object leading to the point in the destination room.

>If this is an *inter-shard* portal, then this property contains an object with shard and room string properties. Exact coordinates are undetermined, the creep will appear at any free spot in the destination room.

Original issue:
bonzaiferroni#6

### Future
Would like a more advanced model of the portal that reminds a lot more of a portal, something that "shimmers" / animates, perhaps lightning coming out from it?
, perhaps like a "platform" and we can shoot a blue beam out of it? this will allow creeps to "crawl" into the platform?
perhaps an animation upon a creep leaving, / entering a portal.

Alternatives / ideas / tutorials
![image](https://user-images.githubusercontent.com/9084377/63212791-c413a900-c109-11e9-920d-0545c0373666.png)
https://youtu.be/w0znZIuvQ2I

**Comment by thmsndk** [comment]
KittyTack on slack suggested the following visuals
> portal could be a pulsing blue sphere

**Comment by thmsndk** [comment]
Initial unpacking and rendering of portals
![image](https://user-images.githubusercontent.com/9084377/63024392-697b1280-bea7-11e9-8993-c64b65403aae.png)

**Comment by thmsndk** [comment]
Toying with particle effects as a rendition of Portals instead of the blue cylinder
![particle-portal](https://user-images.githubusercontent.com/9084377/63138937-9c72f280-bfdc-11e9-88eb-1fb1e1c66ecc.gif)

**Comment by thmsndk** [comment]
🤔
![image](https://user-images.githubusercontent.com/9084377/63139737-9d595380-bfdf-11e9-812d-aa158ad9e539.png)

**Comment by thmsndk** [comment]
Scaled it a little
![image](https://user-images.githubusercontent.com/9084377/63140176-45bbe780-bfe1-11e9-89a6-23a8299b1f7a.png)
![image](https://user-images.githubusercontent.com/9084377/63140217-79970d00-bfe1-11e9-8aaa-8b6c2d8f2d88.png)

**Comment by thmsndk** [comment]
Looks a little silly in shard0 E70S5 where there is a "wall" of portals 🤔 but seems to run smoothe on my system
![image](https://user-images.githubusercontent.com/9084377/63160117-4bcfb980-c01d-11e9-8a05-a42d04d4d6a2.png)
![image](https://user-images.githubusercontent.com/9084377/63160152-5c802f80-c01d-11e9-99f4-0130384090ab.png)

**Comment by thmsndk** [comment]
Without the platform
![image](https://user-images.githubusercontent.com/9084377/63213851-6d11d200-c111-11e9-80ef-275790c1ea8e.png)

**Comment by Robalian** [comment]
now perspective can trick you, maybe you could try having it lower on the ground. If it doesn't look right I'd go with the ones with a platform

**Comment by thmsndk** [comment]
Lowered it more the to ground end sized the center a little smaller, it's random between 1 and 4
![image](https://user-images.githubusercontent.com/9084377/63225892-e7a42580-c1d5-11e9-9cdc-2819d5afc9a7.png)

**Comment by thmsndk** [comment]
8 Portals in a "square"
![image](https://user-images.githubusercontent.com/9084377/63229166-eab30c00-c1fd-11e9-9a18-62b808fbc7b4.png)

**Comment by thmsndk** [comment]
@Robalian suggested the following for the spawn /teleport effect
https://www.youtube.com/watch?v=M_XwzBMTJaM&feature=youtu.be&t=161
![image](https://user-images.githubusercontent.com/9084377/63262666-db2bd580-c286-11e9-9ab4-82ba1fb7bd12.png)
![image](https://user-images.githubusercontent.com/9084377/63262634-c51e1500-c286-11e9-89b0-afc4c170f176.png)

**Comment by thmsndk** [comment]
Portals now rendered in "mapview"
![image](https://user-images.githubusercontent.com/9084377/63803609-99013480-c915-11e9-9f84-9bd468da18b2.png)
