### ISSUE TITLE
Season 1 support

### ISSUE THREAD

**Issue by Gadjung** [thmsndk/Screeps3D#231]
New Structure:
- animated (pulsating/rotated)
- snowflake-like shape
- navy-blue - yellow color
- altar-like ?

New resource:
- animated (pulsating)
- snowflake-like shape
- navy-blue - yellow color

**Comment by Gadjung** [comment]
Twitter with short gif presenting how it looks: 
https://twitter.com/ScreepsGame/status/1315957482527830021

**Comment by thmsndk** [comment]
We also might want a specific spectate mode for seasonal for streaming, comments from slack:

> early game just track the rooms with the highest RCL
> And/or the players with the highest GCL
> Once score starts ticking in, track the top 10 players
> Focusing on combat and general claimed room stuff
> you probably would want to apportion airtime by sum of RCLs.  (e.g. show a player with sumrcl 30 30 times more than a player with sumrcl 1
