### ISSUE TITLE
[Linux] Can't Click any buttons in the main menu

### ISSUE THREAD

**Issue by ghost** [thmsndk/Screeps3D#246]
I can't click any button in the main menu after opening the game (Version 0.0.11). They get highlighted while hovering the mouse over them but nothing happens when I click them. My Laptop is relatively low-spec and the system requirements on linux seem to be very high currently, so the issue might be related to that. The dev console buttons work fine though. The console shows this upon launch:

`NullReferenceException: Object reference not set to an instance of an object`
`> Screeps_API.ScreepsLogin.Start () (at C:/Projects/Screeps3d/Assets/Scripts/Screeps_API/ScreepsLogin.cs:63)`

Here's some general information about my machine (a lenovo ideapad 3):

**OS**: Void Linux 
**Kernel Version**: 5.12.19_1
**CPU/GPU**: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
All Drivers should be set up correctly AFAIK, I can play relatively complex 3d titles like No Man's Sky just fine, also other Unity games.

**Comment by thmsndk** [comment]
Hi @Dangertech 

It could be a problem with our latest additions in regards to the SS3, it could also be because of merge errors based on the line number you have supplied from the stacktrace

https://github.com/thmsndk/Screeps3D/blob/afa8e36cd56b6b9be5cd6350ba46b9180cd775ad/Assets/Scripts/Screeps_API/ScreepsLogin.cs#L63

That would indicate _chooseSS3UnifiedCredentialsFileLocationPopup being null or not set properly in the scene.

**Comment by thmsndk** [comment]
It is also only something that triggers if you do not have a SS3 credentials file so it might have slipped trough the gates when I verified it before release.

**Comment by thmsndk** [comment]
@Dangertech as a temporary workaround, could you create this file https://github.com/screepers/screepers-standards/blob/master/SS3-Unified_Credentials_File.md and see if the issue persists?

Make sure it does not have the `config:` part and if you place the config file near the executable, it should be named `.config.yml`

**Comment by thmsndk** [comment]
Should be fixed in 0.0.12
https://github.com/thmsndk/Screeps3D/releases/tag/0.0.12
