### ISSUE TITLE
[Idea] make ramparts render like forcefields

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#28]
Hexcede on slack suggested ramparts should look like forcefields and linked a tutorial video 

https://www.youtube.com/watch?v=NiOGWZXBg4Y
![image](https://user-images.githubusercontent.com/9084377/59968117-9872a900-9534-11e9-8801-d48fb7b2c61b.png)

ramparts should be "connected" together aswell so it is only the "true" edges that are rendered as an edge.

The tutorial appears to require unity 2019 though, but it would be pretty awesome if we could accomplish this one day.

**Comment by Gadjung** [comment]
It's done i guess :)
![image](https://user-images.githubusercontent.com/8514638/88461029-dc0ab580-cea0-11ea-883c-a8a134344317.png)
