### ISSUE TITLE
Spawning sidepanel does not reset and is rendered in a weird manner

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#31]
![odd-spawn-sidepanel](https://user-images.githubusercontent.com/9084377/59974829-c3024780-95b0-11e9-90df-dea230cccb7f.gif)

It seems to me like the panel does not reset when not spawning anything, and what is the numbers that are shown 23/24 is that the time to spawn? 🤔

**Comment by Robalian** [comment]
It's spawn time in ticks, in a form of progress bar instead of countdown.
