### ISSUE TITLE
Ghost creeps

### ISSUE THREAD

**Issue by Robalian** [thmsndk/Screeps3D#4]
Sometimes creep that should die isn't removed from map and instead stands still with negative TTL.

Steps to reproduce: Let it run on spectator mode until you spot some should-be-dead creeps. Easiest to spot near sources.

**Comment by Robalian** [comment]
Better steps to reproduce: Find some creep with small TTL, leave room where it is (room should be unsubscribed) and wait until creep should have died. Enter the room back. Creep is still there, with negative TTL.

**Comment by thmsndk** [comment]
https://github.com/bonzaiferroni/Screeps3D/issues/27

**Comment by Robalian** [comment]
Reproduced with StructureRoad - if we're not subscribed to room where road is supposed to dissappear (tested with dismantler creep) the road stays there. Reconnecting to server fixes it. I'm assuming it's a problem with all kinds of RoomObjects.

Edit: Confirmed for spawns and extensions by dismantling MichaelBots room.
