### ISSUE TITLE
Incorporate shader graph and other hdrp/lwrp unity items

### ISSUE THREAD

**Issue by ssmith151** [thmsndk/Screeps3D#53]
https://github.com/Unity-Technologies/ScriptableRenderPipeline/wiki/Upgrading-to-HDRP

If the goal is to have fancy shaders for features like shields and textured swamps, it might be helpful to upgrade unity to lower the required learning period by using shader graph.

The project seems to work perfectly without the hdrp currently.  It is mainly a solution to the other requests for 'fancy' graphics like that hexagonal shield look, as the videos for that use shader graph.

Done:

- [x] mapped materials to HDRP
- [x] tuned down skybox and fog
- [x] changed some colors so it's less pastel-white-grey
- [x] added some normal textures (to swamps and ground) to check how it behaves

still to do :
- [ ] adjust emissions
- [ ] remove/fix bloom
- [ ] simplify and adjust materials usage across structures
- [ ] creep body is not migrated properly

**Comment by thmsndk** [comment]
I tried installing the HDRP plugin and got some errors in console about the scripting language, we might not be able to do this before we are on C#7 :/ #25

**Comment by ssmith151** [comment]
My thought is the project is moving smoothly without it.  If some level of 'professional' graphics is desired later, this could be helpful.  No harm in leaving this undone until then.  If there are some shaders that we do need, there are a few good ones out there written in the just plain code style.

**Comment by thmsndk** [comment]
HDRP branch seems to be working nicely so far. closing.
