### ISSUE TITLE
[Suggestion] Visualize Nukes

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#58]
There was talk on slack about visualizing when a nuke hits a target, rendering a mushroom cloud. this got me thinking it would also be cool to render an in air missile flying in an arc from launch room to target room and destination (x,y)
![image](https://user-images.githubusercontent.com/9084377/61142807-f6aa0080-a4d0-11e9-88d5-86e16a31e101.png)

- [x] Animate missile launch from launch room
- [x] visualize launched missile in air space
  - [ ] Visualize pending missile impact on target room
- [ ] Visualize missile impact on target room

Need to get some screenshots of the official client to see how it looks while the nuke is in air, and what it looks like on impact.

## Inspiration:
![image](https://media.giphy.com/media/yoJC2mtLhd0v19pJbW/giphy.gif)
https://youtu.be/Adhp0epshfg?t=65
https://www.youtube.com/watch?v=7hTPTiAHZxk

### Tutorials
Rendering a Launch Arc in Unity
30m https://www.youtube.com/watch?v=iLlWirdxass
https://en.wikipedia.org/wiki/Projectile_motion

Moving Object Along A Parabola | Unity Tutorial 
https://www.youtube.com/watch?v=ddakS7BgHRI

Shader Forge - Particle Dissolver Shader
https://www.youtube.com/watch?v=IZryS_dsqdg

## Endpoint
official experimental api for nukes
>https://screeps.com/api/experimental/nukes

Support added by ags131 in screepsmod-admin-utils after we talked about this feature in slack
>https://github.com/ScreepsMods/screepsmod-admin-utils/compare/243bc5f71a6b...ce722fba832b

```
{
	"ok": 1,
	"nukes": {
		"shard0": [],
		"shard1": [],
		"shard2": [{
				"_id": "5d26127173fcd27b55a7ef39",
				"type": "nuke",
				"room": "W23S15",
				"x": 12,
				"y": 37,
				"landTime": 17300541,
				"launchRoomName": "W31S18"
			}, {
				"_id": "5d26aa11385277180e5c2187",
				"type": "nuke",
				"room": "W22S22",
				"x": 23,
				"y": 22,
				"landTime": 17311981,
				"launchRoomName": "W17S28"
			}
		],
		"shard3": []
	}
}
```

**Comment by thmsndk** [comment]
Crude, initial WIP, but it does render an arc, and renders the "missile" on the arc

![image](https://user-images.githubusercontent.com/9084377/65463085-6cc6ce00-de57-11e9-8b5c-3733fa49ff6c.png)
![image](https://user-images.githubusercontent.com/9084377/65463152-997ae580-de57-11e9-9756-29d46f23bdcb.png)

**Comment by thmsndk** [comment]
Research about real life nukes
![image](https://media.trytn.press/titanmissilemuseum/2019/02/Titan-Missile-Museum-Photo-Galley-10.jpg)
"How to Launch a Nuclear Missile"
https://www.youtube.com/watch?v=knDIENvBTgw
https://titanmissilemuseum.org/

**Comment by thmsndk** [comment]
> gondala with balloons propellers and s lil steam punk creep holding a bomb
<sub>[View in Slack](https://screeps.slack.com/archives/C0HJGK1L2/p1569431823325500)</sub>

**Comment by thmsndk** [comment]
![image](https://user-images.githubusercontent.com/9084377/67607310-5f697000-f784-11e9-8105-4658b37ccc4b.png)

We have these issues

- [ ] arc is not removed when nuke is done
- [ ] nuke missile is not removed when done
- [ ] nukes position is from it's base instead of the tip, so it will first explode when all the way into the ground.
- [ ] the nuke is reeeeeeeallly slow
we need to make it launch slow, gaining  more speed, then spending most of it's time in the air/ in the middle, as it gets closer to impact it should be gaining more and more speed, so it comes crashing down on the target. instead of slowly inching it's way into the ground.

**Comment by thmsndk** [comment]
Perhaps this purple one, or something along that, except it should not get slower at the end
![image](https://user-images.githubusercontent.com/9084377/67607844-321dc180-f786-11e9-8e9c-9798dfd070f1.png)

![image](https://user-images.githubusercontent.com/9084377/67607835-2af6b380-f786-11e9-9cd7-1e7e9605ef7f.png)

https://www.desmos.com/calculator/u2qz73ufju

**Comment by thmsndk** [comment]
Notes from slack when I asked if anyone where bored enough to make a function for the nuke speed:

faff
>float speed = (t < 0.5 ? sin(t*2*PI) : sin((t-0.5)*PI)) * baseSpeed?
>rather than accurate representation of motion you just want it to feel nice and roughly corresponding to the stage in its flight, so I think this'd work
probably you'd use some ratio of speed and baseSpeed so that it's never just static in the air
w/ t = ticksInFlight / totalFlightTicks

orlet
```
function f(x)
{
    return 2.0276 - Math.pow(x - 1.1666, 2) - (1 / (1.5 - x));
}
this is the function, x = [0..1]

also, according to wolfram alpha, integral of this function is
function int_f(x)
{
    return -0.0000222267*x + 1.6666*x*x - 0.333333*x*x*x; // -0.0000222267 x + 1.6666 x^2 - 0.333333 x^3
}
in case you need it :smile:
```

**Comment by Gadjung** [comment]
on current new_nuke branch, remaining features should be implemented:
- proper arc
- smoke trail
- launch smoke in starting phase
- explosion
- nuke target display in target room
![image](https://user-images.githubusercontent.com/8514638/88460964-5be45000-cea0-11ea-9993-79212c7d57e3.png)
![image](https://user-images.githubusercontent.com/8514638/88460966-60a90400-cea0-11ea-9bc0-fef2c82901c3.png)
![image](https://user-images.githubusercontent.com/8514638/88461919-188ddf80-cea8-11ea-8d8a-9495944076c0.png)

**Comment by Gadjung** [comment]
full lifecycle https://www.dropbox.com/s/nwdeyuk7j13bjge/Nuke3.mp4?dl=0
