### ISSUE TITLE
[Feature Request] Support the SS1 Unified Credentials File

### ISSUE THREAD

**Issue by AlinaNova21** [thmsndk/Screeps3D#64]
I would love to see support for the [SS1 Unified Credential File][0], most of my PCs already have the configs laying around since all my tools use them.
Could potentially use it to pre-populate a server list, and since it contains auth data, could skip the login.

[0]: https://github.com/screepers/screepers-standards/blob/master/SS3-Unified_Credentials_File.md

**Comment by thmsndk** [comment]
@ags131 would you expect to be able to point to a location to find this credential file, or should the user dump it into a specific directory, or how is the usage?

Also, random links for yml parsing
https://stackoverflow.com/questions/25650113/how-to-parse-a-yaml-string
https://github.com/aaubry/YamlDotNet (Available at Unity Asset Store)
https://github.com/xoofx/SharpYaml

**Comment by AlinaNova21** [comment]
Hence the spec, it has a list of locations to find the file in ;)

**Comment by AlinaNova21** [comment]
- Env Variable ($SCREEPS_CONFIG)
- Project Root (Optional) - (project/.screeps.yaml)
- Current Working Directory - (./.screeps.yaml)
- XDG Config Directory - ($XDG_CONFIG_HOME/screeps/config.yaml)
- XDG Config Default Directory - ($HOME/.config/screeps/config.yaml)
- APPDATA (Windows Only) - (%APPDATA%/screeps/config.yaml)
- Home Directory - (~/.screeps.yaml)

**Comment by thmsndk** [comment]
Next time, i'll read the spec before asking questions then 😆

**Comment by thmsndk** [comment]
This Unity Asset mentioned in the last comment
https://assetstore.unity.com/packages/tools/integration/yamldotnet-for-unity-36292
seems to have all the bells and whistles we need :)

@ags131 i'm not sure what `$XDG_CONFIG_HOME` is, is that something linux specific? or an environmentvariable, we gotta remember MAC aswell 🤔

**Comment by AlinaNova21** [comment]
`$XDG_CONFIG_HOME` is an environment variable in linux, although I think it exists for some mac setups too
All variables prefixed with `$` like `$HOME` are environment variables, its the linux/mac way of denoting them. (While windows does `%APPDATA%`)

Some more reference data: 
go-screeps config structure: https://github.com/screepers/go-screeps/blob/master/config/config.go
go-screeps loader: https://github.com/screepers/go-screeps/blob/master/config/loader.go
screeps-api fromConfig: https://github.com/screepers/node-screeps-api/blob/master/src/ScreepsAPI.js#L18-L66

**Comment by thmsndk** [comment]
Can probably use this to get environment variables, would have to test it I guess 🤔 
https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?redirectedfrom=MSDN&view=netframework-4.8#System_Environment_GetEnvironmentVariable_System_String_

**Comment by thmsndk** [comment]
> <@UK28UEQ22> Leave the `$` out when getting the variables, the `$` is linux/bash specific syntax <https://github.com/thmsndk/Screeps3D/blob/develop/Assets/Scripts/Screeps_API/ServerListProviders/SS3UCFServerListProvider.cs#L135-L140>
<sub>[View in Slack](https://screeps.slack.com/archives/CKL4441DW/p1591106097322000)</sub>

**Comment by thmsndk** [comment]
> Yep! You don't support `.yml` :stuck_out_tongue:
<sub>[View in Slack](https://screeps.slack.com/archives/CKL4441DW/p1591109997323100)</sub>
