### ISSUE TITLE
Add PTR store update support

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#67]
Add support for the new storage syntax / system

source
```json 
{
	"_id": "5bbcae129099fc012e63861d",
	"room": "E19S38",
	"type": "source",
	"x": 5,
	"y": 20,
	"energy": 2310,
	"energyCapacity": 3000,
	"ticksToRegeneration": 300,
	"invaderHarvested": 41634,
	"nextRegenerationTime": 1.043212E+07
}
```

container
```json 
{
	"_id": "5d631296ac2d2d20dcf64875",
	"type": "container",
	"x": 6,
	"y": 21,
	"room": "E19S38",
	"notifyWhenAttacked": true,
	"hits": 250000,
	"hitsMax": 250000,
	"nextDecayTime": 1.043206E+07,
	"store": {
		"energy": 378,
		"GO": 52
	},
	"storeCapacity": 2000
}
```
spawn
```json 
{
	"_id": "5cf3b2f83dca297f761ca396",
	"type": "spawn",
	"room": "E19S38",
	"x": 11,
	"y": 32,
	"name": "Spawn1",
	"user": "5a44e109ac5a5f1d0146916e",
	"hits": 5000,
	"hitsMax": 5000,
	"spawning": null,
	"notifyWhenAttacked": true,
	"off": false,
	"store": {
		"energy": 64
	},
	"storeCapacityResource": {
		"energy": 300
	}
}
```

**Comment by thmsndk** [comment]
Added some "basic" PTR store update support

- towers
- spawn 
- powerspawn
- extensions
- labs
- nuker
 where broken, I need to iterate some more on it to fix labs,nuker and powerspawn "properly"

![image](https://user-images.githubusercontent.com/9084377/64744685-0cee3000-d505-11e9-9095-7542464ab827.png)

**Comment by thmsndk** [comment]
Need help verifying if there are any missing issues with the store update.

**Comment by duckymirror** [comment]
Labs don't show the correct capacity when they're empty.
![Capacity: 2000](https://user-images.githubusercontent.com/33291860/79074082-ae7f6f00-7cea-11ea-9c0d-78bc36d3d165.png)
Labs have a total capacity of 5000.

#117 might be related to this too.

**Comment by thmsndk** [comment]
@duckymirror the issue seems to be when there is only energy present in the lab. then the capacity is delivered as 2000 for energy, but because there is no other resource present. that capacity does not exist. e.g. the following dataset is recieved. I guess we could parse storeCapacity secondary. currently it is overridden if storeCapacityResource is present

```json
{
	"_id": "5c28ce2b904c1946be603623",
	"type": "lab",
	"x": 19,
	"y": 7,
	"room": "W32N19",
	"notifyWhenAttacked": true,
	"user": "5928c387f604024177457eae",
	"hits": 500,
	"hitsMax": 500,
	"cooldown": 0,
	"actionLog": {
		"runReaction": null,
		"reverseReaction": null
	},
	"store": {
		"energy": 1600,
		"OH": 0,
		"KH2O": 0,
		"XKH2O": 0,
		"KH": 0,
		"XUHO2": 0,
		"XGHO2": 0,
		"XLHO2": 0,
		"GH2O": 0,
		"XGH2O": 0,
		"GHO2": 0,
		"XZH2O": 0,
		"KO": 0
	},
	"storeCapacityResource": {
		"energy": 2000,
		"OH": null,
		"KH2O": null,
		"XKH2O": null,
		"KH": null,
		"XUHO2": null,
		"XGHO2": null,
		"XLHO2": null,
		"GH2O": null,
		"XGH2O": null,
		"GHO2": null,
		"XZH2O": null,
		"KO": null
	},
	"cooldownTime": 1,
	800456E+07,
	"storeCapacity": 5000
}

```
