### ISSUE TITLE
Selection isn't removed for objects that don't exist anymore

### ISSUE THREAD

**Issue by duckymirror** [thmsndk/Screeps3D#75]
If an object is selected while it's destroyed / dies / decays the selection isn't removed. The selection panel can be closed by clicking somewhere in the room, but the circle around the selected object stays forever.
![image](https://user-images.githubusercontent.com/33291860/65370576-9e267a80-dc5a-11e9-8ea0-f07dc91de8e7.png)

**Comment by thmsndk** [comment]
Currently a work around exist for removing the selection circle, I can't exactly remember what I did, but I think I  clicked on the middle of the ground without selecting anything, and something with the rectangle selection. The selection script needs to be aware of when objects are unloaded though :)

**Comment by thmsndk** [comment]
https://github.com/thmsndk/Screeps3D/blob/c02f1d9cf9c375911eb1adf146674a9e77059067/Assets/Scripts/Screeps3D/Tools/Selection/Selection.cs#L52-L57
