### ISSUE TITLE
initial stronghold support

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#79]
![image](https://user-images.githubusercontent.com/9084377/67025943-28051e80-f107-11e9-96ec-9170f7d32af7.png)

![image](https://user-images.githubusercontent.com/9084377/67025881-0d32aa00-f107-11e9-821e-dba7d160a4cf.png)

![image](https://user-images.githubusercontent.com/9084377/67025864-07d55f80-f107-11e9-97b5-9bea54c0c880.png)
Aaaaaand more research needs to be done in regards to different levels, what data we recieve, and so forth

**Comment by thmsndk** [comment]
Currently the stronghold from the above post is rendered like this in 3D
![image](https://user-images.githubusercontent.com/9084377/67026348-ddd06d00-f107-11e9-8ca7-822d4de04546.png)
Roads are missing, it aint colored red and the invader core is not rendered

**Comment by thmsndk** [comment]
A purple beam is emitting from the invader core targeting the controller

![image](https://user-images.githubusercontent.com/9084377/71566017-59f61200-2ab4-11ea-89dc-703a834e9eeb.png)

The controller is also pulsating with a red glow around it 
![image](https://user-images.githubusercontent.com/9084377/71566057-94f84580-2ab4-11ea-8033-2984d66a73e5.png)

**Comment by Gadjung** [comment]
me do dis
