### ISSUE TITLE
rangedMassAttack is wrongly rendered as a beam, should be an AOE effect

### ISSUE THREAD

**Issue by Robalian** [thmsndk/Screeps3D#8]

**Comment by duckymirror** [comment]
This happens when the creep uses `rangedMassAttack` instead of `rangedAttack`.

**Comment by thmsndk** [comment]
It seems like we receive an empty target for the rangedMassAttack, and thus cannot render where the attack is hitting 🤔 
![image](https://user-images.githubusercontent.com/9084377/65169922-e588ed00-da47-11e9-83dc-77d2af14c344.png)

**Comment by thmsndk** [comment]
rangedMassAttacks works the following way
> It's anything non-friendly in range 3 takes 10-4-1 based on distance.

So in fact, it makes no sense to render a beam for rangedMassAttack, we should instead render an AOE effect.

the official client renders a circular pulse expanding out from the creep, starting bright and dimming to nothing.

Additionally the following are immune to the rangedMassAttack
> walls, roads, and containers
> basically, unowned structures

**Comment by thmsndk** [comment]
Made a temporary/initial RMA effect inspired by this guide https://www.youtube.com/watch?v=uR2jcU3x3kU
![image](https://user-images.githubusercontent.com/9084377/71758524-02cfb300-2ea1-11ea-8091-f5514ff8b746.png)
