### ISSUE TITLE
initial ruin support

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#80]
![image](https://user-images.githubusercontent.com/9084377/67026090-6c90ba00-f107-11e9-8037-2574bc73c0f8.png)

- [x] Render structures/roomobjects instead of ruins
- [ ]  Figure out to do when multiple ruins are placed on the same tile, with real structures ontop of them.

**Comment by thmsndk** [comment]
Had not considered how it would look with both a ruin and a new structure occupies the same spot 🤔 

Taken note of the extension inside the storage ruin, and the "extra" tower inside the tower.
![image](https://user-images.githubusercontent.com/9084377/79105452-f77a0680-7d70-11ea-8280-c6ad2674c9cb.png)

Hmm, I was considering making ruin towers point downwards towards the ground with the barrel.

Ideas / suggestions are welcome :) this seems to work as initial ruin support instead of the "ruin not implemented" placeholder atleast :)

**Comment by Gadjung** [comment]
a holographic material might solve partially problem of recognizing what is a `proper` object on given cell

**Comment by Gadjung** [comment]
Current solution :
https://www.dropbox.com/s/ypggblhte579act/Ruin4.mp4?dl=0
