### ISSUE TITLE
support for factory

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#84]
https://docs.screeps.com/api/#StructureFactory
https://docs.screeps.com/resources.html#Commodities

Factories are used to
- Compress and decompress commodities
- Make basic regional commodities
- make higher commodities
- make chains
  - mechanical
  - biological
  - electrical
  - mystical

A factory can have different levels, how do we visualize what level a factory is at?
a factory has "ingredients" in its [store](https://docs.screeps.com/api/#StructureFactory.store) how do we visualize what ingredients are in the store, e.g. commodities

Should we visualize what kind of product that is being `.produce`ed? with some sort of effect.

**Comment by thmsndk** [comment]
> Factory
• windows on each side
• we have 4 windows, and the highest reaction takes 3 windows
• we could fill each window with a color indicating what is actually being used to make something, and the fourth window could indicate the output / be filled up as the action progresses.
• If we are crafting bars, bars should be spitting out
• If there are bars present bars should be scattered around the ground (this could apply to the storage as well)
• different animations for different actions being crafted
• you mentioned the lights indicating the leve (not sure how we should render this) - but it could be lights going up the sides of it
<sub>[View in Slack](https://screeps.slack.com/archives/CKL4441DW/p1575417893178000)</sub>

**Comment by thmsndk** [comment]
For now, this is the temporary model, indicating used capacity vs total capacity
![image](https://user-images.githubusercontent.com/9084377/70100741-00c0cd00-1633-11ea-9a2c-08d023a076da.png)

We need to solve visibility issues when looking through an empty factory
![image](https://user-images.githubusercontent.com/9084377/70100791-2bab2100-1633-11ea-9c16-065f0f025fdf.png)

And we need to add energy champers, gears / moving parts, perhaps a smoke effect when it is actively working?

**Comment by Gadjung** [comment]
I've created some propositions for models based on already present one:

![Factory_Prev](https://user-images.githubusercontent.com/8514638/72680022-489d9580-3ab5-11ea-8cff-0e305b222ed1.PNG)

i've created a branch but have no permissions to push it

**Comment by thmsndk** [comment]
@Gadjung you make a fork, make your branch in your fork, and then make a pull request from your fork to this repos develop  branch

**Comment by thmsndk** [comment]
#189 Adds a new factory with some pretty nifty visuals
