### ISSUE TITLE
Separate server cache and credentials cache

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#87]
The serverlist currently consist of a "ServerCache". this cache is persisted to a binary file, containing all servers and credentials for theese servers.

Instead we should have 3 seperate files
- A file containing all manually added servers
- A file containing credentials to servers
  - If credentials are supplied by a ServerSourceProvider, theese credentials should not be persisted in this credentials file.
  - It should be possible to persist multiple credentials to the same server.
  - It should be possible to connect without persisting credentials to a file (Save checkbox)
- A file containing stats for servers
  - This file can contain amount of users, likes, last online,  availability
  - last time connected to server.

This way, servers provided by "third party" sources are not cached in anything other that the stats file. Third party sources should be able to supply multiple credentials to a server.
As a simple solution each pair of credentials could cause a new entry in the server list.

Theese files should be versioned in some way, such that older versions can be migrated to newer versions.

**Comment by thmsndk** [comment]
Perhaps we should just embrace the SS3 Unified Credentials file, even for manually added servers?

**Comment by thmsndk** [comment]
Work in progress, initial dialog for showing potential locations.
![image](https://user-images.githubusercontent.com/9084377/115147666-5e08c300-a05c-11eb-89da-c2baf77a6770.png)

**Comment by AlinaNova21** [comment]
I would just filter it to one extension in the dropdown to make it a bit more user friendly

**Comment by thmsndk** [comment]
Limited to `.yml` files
![image](https://user-images.githubusercontent.com/9084377/115905319-394e8a00-a466-11eb-9d88-93fef447d000.png)

We also now persist the official server list in a cached file and restore it in case of the official server list not responding
![image](https://user-images.githubusercontent.com/9084377/115905562-8e8a9b80-a466-11eb-80d8-55fc867874aa.png)

**Comment by thmsndk** [comment]
Considering I'm messing around with the server browser, are there any enhancements that could be done to it? or anything people feel they are missing?

![image](https://user-images.githubusercontent.com/9084377/115932534-6eba9e00-a48d-11eb-9d42-019feede9440.png)

**Comment by Gadjung** [comment]
could add a check of what state we're on the server, spawned / not spawned ?

**Comment by Gadjung** [comment]
or quick check how many rooms are owned (not sure if possible / worthwhile)

**Comment by Gadjung** [comment]
could also provide the (i) icon with server message on hover ;)

**Comment by thmsndk** [comment]
Good suggestions, they all require additional calls to endpoints though.

> could add a check of what state we're on the server, spawned / not spawned ?

Would require an additional call to get world state, but could be doable
![image](https://user-images.githubusercontent.com/9084377/115933129-8c3c3780-a48e-11eb-850c-f0c0a8fc4d59.png)


> or quick check how many rooms are owned (not sure if possible / worthwhile)

Would require an additional call to an endpoint 
- https://screeps.com/api/user/rooms?id={id} requires us to supply the userId
- `https://screeps.com/api/user/overview?interval=8&statName=energyHarvested` if we want additional data, but that requires us to have authenticated first.

- `/api/user/find?username=thmsn` can give us the badge, userId and gcl without being authenticated, but we don't have the username on official


> could also provide the (i) icon with server message on hover ;)

We get this with the api/version call, that we already call. the issue is that it is html, so we would need to parse it in a feasible manner to present it. also #157 
 S+ example:

![image](https://user-images.githubusercontent.com/9084377/115933316-ea691a80-a48e-11eb-9e48-5e1f61681ac1.png)

I was also considering looking at the "features" part of api/version, showing what mods are installed if they have added it to the features part.
![image](https://user-images.githubusercontent.com/9084377/115934183-bdb60280-a490-11eb-8b03-a066c965dc44.png)

**Comment by AlinaNova21** [comment]
For private servers, you can hit `/stats` to get some info including owned room counts. Can probably lookup the user in that list. Thats added by `screepsmod-admin-utils`, so you can also detect its availability via the features. (Although most servers already run it)
![image](https://user-images.githubusercontent.com/1013519/115939279-47e77200-a463-11eb-8791-0e626a69dd49.png)

**Comment by Gadjung** [comment]
also getting and displaying 'shardName' (and not allowing to connect until it's obtained) should prevent some issues after connection

**Comment by thmsndk** [comment]
> also getting and displaying 'shardName' (and not allowing to connect until it's obtained) should prevent some issues after connection

That is part of api/version, and I should have fixed it my issuing a version call when you select the server :)

But I guess we could display shardnames 🤔 at least if there is only 1, not sure what to display on mmo

**Comment by Gadjung** [comment]
all the shards on mmo ? can also hardcode them since i dont think they'll change

**Comment by thmsndk** [comment]
New edit server dialog
Official
![image](https://user-images.githubusercontent.com/9084377/115958774-175a1380-a509-11eb-8813-8d7e2607da36.png)
Private
![image](https://user-images.githubusercontent.com/9084377/115958795-33f64b80-a509-11eb-8a31-c376636b3b64.png)

**Comment by AlinaNova21** [comment]
> all the shards on mmo ? can also hardcode them since i dont think they'll change

I wouldn't hardcode them, just pull the shards array from /api/version since mmo does have that too.

**Comment by AlinaNova21** [comment]
@thmsndk Might want to add protocol to that, just a `http` and `https` dropdown should be enough. Or a `secure` checkbox since thats how UCF does it. I don't like the idea of assuming 443 is always https and others aren't. (I might decide to use 8443 for a testing server or something!)

**Comment by thmsndk** [comment]
Added a SSL checkbox below port
![image](https://user-images.githubusercontent.com/9084377/116205840-72c11700-a73e-11eb-9f77-dc6cc2283248.png)

**Comment by thmsndk** [comment]
Well... this is looking rather terrible 😆 
![image](https://user-images.githubusercontent.com/9084377/117325551-1b831b00-ae91-11eb-83b5-3dcdcf9459f9.png)
![image](https://user-images.githubusercontent.com/9084377/117325577-2342bf80-ae91-11eb-94d0-7c1408366603.png)

**Comment by thmsndk** [comment]
Calling auth/me to get the badge on the server, this also gives us the username and id
![image](https://user-images.githubusercontent.com/9084377/120566184-01484880-c40f-11eb-9ebd-64bc3949b636.png)

**Comment by thmsndk** [comment]
![image](https://user-images.githubusercontent.com/9084377/120715517-fa7c0d00-c4c4-11eb-9005-7b3289c6d3b6.png)

**Comment by thmsndk** [comment]
![image](https://user-images.githubusercontent.com/9084377/121595613-bb0e6d00-ca3e-11eb-848d-e9f109385753.png)
![image](https://user-images.githubusercontent.com/9084377/121595663-c8c3f280-ca3e-11eb-8b77-ff30587fc8ed.png)
![image](https://user-images.githubusercontent.com/9084377/121595833-fdd04500-ca3e-11eb-9b82-2dbe6ec163ed.png)
