### ISSUE TITLE
Add reservation indicator on room controller

### ISSUE THREAD

**Issue by Robalian** [thmsndk/Screeps3D#9]
Currently the only way to check if room is being reserved is by selecting source and checking its energyCapacity

**Comment by Flya** [comment]
I have added reservation panel 
<img width="77" alt="image" src="https://user-images.githubusercontent.com/1263053/81129694-d9f22400-8f4d-11ea-98be-2b46e64a3ce7.png">
Do you have any idea how you want to show it on room object?

**Comment by thmsndk** [comment]
@Flya Good job, what is the number in parenthesis though? if it is the cooldown, check out the cooldown panel, it has a progressbar you could render the reservation cooldown like that.

I'm not sure how the we should show the reservation on the actual roomobject
