### ISSUE TITLE
Store widget is not updating each tick for storage

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#91]
As seen here, only capacity keeps updating, the store rendering of energy is "stale" untill you reselect it

![image](https://user-images.githubusercontent.com/9084377/69770789-9c14f680-118a-11ea-9e49-ac549ae1ba60.png)

**Comment by thmsndk** [comment]
And while we a fiddling with this, we might as well sort the store, or make a new issue about sorting it xD

**Comment by M1kep** [comment]
What file controls those UI Elements? Do they have Update functions?

**Comment by thmsndk** [comment]
The StorePanel controls it 
 in general interfaces are used e.g. https://github.com/thmsndk/Screeps3D/blob/c7982040a8d7cd0c3fcfc6db69b4640281cf634e/Assets/Scripts/Screeps3D/Tools/Selection/Subpanels/StorePanel.cs#L22-L25

Seems like this is responsible for sorting
https://github.com/thmsndk/Screeps3D/blob/c7982040a8d7cd0c3fcfc6db69b4640281cf634e/Assets/Scripts/Screeps3D/Tools/Selection/Subpanels/StorePanel.cs#L69-L80
