### ISSUE TITLE
Make plains less plain - well terrain :)

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#98]
Would love to have terrain be less "clean" take a look at Official vs 3D

On official the ground has a texture that makes it a little gritty / varied, i'm wondering if we should slap a random noise texture on that could colorize the plains/swamps/mountains a little like official
@Robalian  suggested to add a perlin noise shader

Official 
![image](https://user-images.githubusercontent.com/9084377/70458609-b87e3080-1ab2-11ea-8fdf-6c36813b9a90.png)
3D
![image](https://user-images.githubusercontent.com/9084377/70458654-d21f7800-1ab2-11ea-946a-1e207caa9f5e.png)

**Comment by Gadjung** [comment]
will look into it on skybox branch.

**Comment by Gadjung** [comment]
i guess it's done and this issue can be closed
![image](https://user-images.githubusercontent.com/8514638/88460821-6520ed00-ce9f-11ea-9421-52290c231278.png)
