### ISSUE TITLE
creep body scaling when damaged

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#99]
`Body.Unpack` is called with no regard for initial payload or not, as a result every delta we recieve , a creeps entire body is replaced, we are not marking a body part as damaged / broken depending on hitpoints. and i'm not certain what we recieve in the following deltas, but judging from what we have seen in the 3d clients when streaming, creeps scale down when being shot.
https://github.com/thmsndk/Screeps3D/blob/c7982040a8d7cd0c3fcfc6db69b4640281cf634e/Assets/Scripts/Screeps3D/RoomObjects/Creep.cs#L85-L111
https://github.com/thmsndk/Screeps3D/blob/c7982040a8d7cd0c3fcfc6db69b4640281cf634e/Assets/Scripts/Screeps3D/RoomObjects/CreepBody.cs#L38-L53

**Comment by M1kep** [comment]
What's the end goal? Creep size should be static from the time of Spawn, or Creep Size should change dynamically based on damaged body parts?

**Comment by thmsndk** [comment]
Euhhmmm, end goal is that creeps scales based on amount of body parts upon spawn.
So a 1 part is as small as it is now, and a 50 part is as big as it is now. if damaged, they should still remain at that scale.

now the body parts are rendered around the creeps, like on official, not exactly sure what happens when they are broken / healed. but that is part of another issue :)

Basicly we want to persist the parts, and update parts  hitpoints accordingly, like when you view a damaged creep on official :)

Again this issue is only about creeps growing / shrinking based on being healed / damaged but we want the body parts in memory to be correct :)
